# Generated by Django 5.1.4 on 2024-12-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_terms_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uploaded_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
