# Generated by Django 5.1.4 on 2025-01-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_customchannel_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customchannel',
            old_name='members',
            new_name='membersPk',
        ),
    ]
